spring:
  application:
    name: eureka
  freemarker:
    prefer-file-system-access: false
server:
  port: 6868
eureka:
  instance:
    ip-address: 127.0.0.1
    prefer-ip-address: true
  client:
    register‐with‐eureka: false #是否将自己注册到eureka中
    fetch‐registry: false #是否从eureka中获取信息
    service‐url:
      defaultZone: http://127.0.0.1:${server.port}/eureka/